| Latest update January 10/2013

#event curseofthefirstborn      "#*#A festering darkness saps your strength#*#
#event presentofthefirstborn    "#*#You are dumbstruck by presence of the firstborn#*#
#event hatchet1         "#*#Hatchet hefts#*#
#event hatchet2         "#*#Hatchet lifts#*#
#event hatchet3         "#*#Hatchet levels#*#
#event hatchet3         "#*#Breakneck hoists an arm back, preparing to lob a weighted mallet in your direction.#*#"
#event hatchet3			##*#You feel a small disruption in the air around you#*#"
#event hatchet4         "#*#Hatchet locks#*#
#event hatchet4         "#*#Breakneck locks eyes with you and snorts#*#
#event hatchet6         "#*#You outdistance the reach#*#
#event hatchet6         "#*#By darting between#*#
#event hatchet6         "#*#Hatchet's axe passes#*#
#event hatchet6         "#*#Breakneck's mallet passes harmlessly overhead#*#"
#event doom             "#*#you sense your doom#*#"
#event doom             "#*#Marked for death#*#"
#event doom             "#*#A dire disease creeps through your veins.#*#
#event doom             "#*#Your skin begins to blister#*#
#event doom             "#*#Your movements become stiff.#*#
#event GazeYou          "#*#gaze of deadly power focusing on you#*#"
#event smotherdecay     "#*#You lose your will to fight#*#
#event plagueofmana     "#*#Your blood is tainted with magical essence#*#"
#event queenlocation    "#*#Sendaii begins to look in your direction#*#"
#event Adds             "#*#You hear a strange buzzing around your head, and feel as though something is creeping toward you.#*#"
#event UquaKey          "The #1# Key must unlock the door to the next room."
#event Silence          "#*#The air stops moving around you#*#"
#event hatchet3         "#*#Devlin Draws back his arm and prepares to snap his whip around your neck.#*#"
#event performer        "#*#Recites a line#*#"
#event devlin           "#*#Devlin's whip snaps around#*#"
#event devlin2          "#*#Devlin's whip snaps aroudn your weapon#*#"
#event Randal1          "Ol' Nilipus hailed from Misty Thicket#*#"
#event Randal2          "Where'er he smelled Jumjum he'd pick it#*#"
#event Randal3          "The halflings grew cross#*#"
#event Randal4          "When their profits were lost,#*#"
#event Randal5          "screamin','Where is that brownie? I'll kick it!'#*#"
#event Seth1            "Another night, in eternal darkness.#*#"
#event Seth2            "Time bleeds like a wound that's lost all meaning.#*#"
#event Seth3            "It's a long winter in the swirling chaotic void.#*#"
#event Seth4            "This is my torture,#*#"
#event Seth5            "my pain and suffering!#*#"
#event seth6            "Pinch me, O' Death. . .#*#"
#event Aelfric1         "Touched tenderly.#*#"
#event Aelfric2         "Where will you be?#*#"
#event Aelfric3         "Dreaming with me.#*#"
#event Aelfric4         "Please,#*#"
#event Aelfric5         "everybody, hear the music.#*#"
#event Britton1         "When she and I split ways,#*#"
#event Britton2         "it felt like the end of my days.#*#"
#event Britton3         "Until I suddenly,#*#"
#event Britton4         "suddenly realized#*#"
#event Britton5         "this life was better off alone.#*#"
#event Britton6         "Solitude was the best gift you ever gave me.#*#"
|#event Brekt           "The Master raises his sword, preparing to slash anyone standing nearby.#*#"
#event fero             "You have succumbed to the ferocity of sullon#*#"
#event wrath            "Your knees tremble from the wrath of sullon#*#"
#event banish           "You have fallen victim to Sullon Zek's vengeance.#*#"
#event wrath            "#*#a bolt of energy surges through you#*#"
#event doom             "#*#fire courses#*#"
#event vergalid1        "#*#You feel yourself being exiled.#*#"
#event vergalid2        "#*#You feel something begin to hatch on your skin.#*#"
#event vertigo          "#*#the world is spinning#*#"
#event vertigo2         "#*#you vision blurs#*#"
#event king             "#*#you notice a glint#*#"
#event deepscar         "#*#boulders begin to unlodge above #1#!"
#event irissa           "#*#your view of the world changes#*#"
#event QueenAdd         "#*#You see the queen glare at you#*#"
#event Meldrath11       "#*#And as for you#*#"
#event Meldrath1        "#*#Support Unit turns to face you#*#"
#event Meldrath2        "#*#Physical translation to location of#*#"
#event charge           "#*#An unstable charge courses through you#*#"
#event Sleeper          "#*#You can't concentrate!#*#"
#event Goodnight        "#*#shamalamadingdongdangfucker#*#"
#event Front            "#*#The mighty prismatic dragon prepares a terrible tail strike!#*#"
#event Back             "#*#Kerafyrm tenses for a charge that will overwhelm his foes!#*#"
#event Back             "#*#Kerafyrm exhales a blast of magical prismatic energy!#*#"
#event mindshear        "#*#You get the feeling that someone is watching you#*#"
#event mindblightNW			"#*#The maw in the southeast#*#"
#event mindblightSW			"#*#The maw in the southwest#*#"
#event mindblightSE			"#*#The maw in the northeast#*#"
#event mindblightNE			"#*#The maw in the northwest#*#"
#event Brekt		      	"#*#Lord Brekt prepares to unleash his fury#*#"
#event Brekt				"#*#The rotocopter's propellers spin rapidly#*#"
#Event BeastOne      "#*#Grunkuck looks at #1# with glee!#*#"
#Event BeastTwo      "#*#Grunkuck looks at #1# with strange intent#*#"
#Event BeastThree    "#*#insane with rage at #*#"
#Event Brells		     "#*#envelops your body #*#"
#Event CV2	     "#*#Seething corruption on YOU!#*#"
#Event ROT		 "#*#The Tentacle Terror Mentor points at you, and#*#
#Event ROT		 "#*#The Turbulance Toad glares at you#*#
#event ROT		 "#*#Spinefreezer's eyes all focus upon you, just#*#
#event Sisters "#*#You are surrounded by debilitating energy#*#"
#event ar1 "#*#Aaryonar turns a dreadful gaze upon YOU!#*#"
#event arl2 "#*#Aaryonar turns his gaze away from you#*#"
#event Blob "#*#MOVE FROM BLOB #*#
#event Totem "#*#Seek out the purity stone to remove the filth that surrounds you #*#"
#event Window "#*#Jump from this tower as the ultimate sacrifice to Sholoth#*#"
#event cekenar "#*#You are charged with a bolt of lightning#*#"
#event danela "#*#dynamite at #*#"
#event chapterhouse "Your bones are burning#*#"
#event zalikor "#*#You have been corrupted by the fear crystal#*#"
#event xorbbfire2 "#*#Your skin ignites#*#"
#event xorbbwhip "#*#Mordaur points a craggy finger and roars at |${Me.CleanName}| #*#"
#event xorbbfire3 "#*#Findlewill begins casting a fireball at#*#"
#Event FindleFireBall    "#*#You feel an inner warmth as Findlewill points at you#*#"
|#Event XorbbEye        "#*#You are consumed by a sense of power watching and hating you#*#"
#event Xorbb3	"King Xorbb shouts '|${Me.CleanName}|'"
|#event Xorbb3Sage "'|${Me.CleanName}|' averted their gaze#*#"

#Event SlaveCourage    "#*#a frightened slave looks courageous#*#"
#Event ChelsMove    "#*#The crowd in the #1# section boos. They want the action brought closer!#*#"
#Event KilsevRage    "#*#Kilsev begins to focus his rage at #1##*#"
#Event KilsevRageOff    "#*#Kilsev's rage subsides#*#"
#Event VyzhAE        "#*#Vyzh`dra draws power from the crowd's energy#*#"
#Event VyzhGetClose    "#*#Vyzh`dra commands his tigers to attack#*#
#Event ChelsStopDPS    "#*#The crowd boos. They think the fight is going too fast#*#
#Event ChelsStopDPS		"#*#Kijarl begins to absorb all damage#*#"
#Event  StartDPS		"#*#Kijarl performs an exceptional heal!#*#"
#event Prime1 "#*#Your flesh begins to bubble and ooze.#*#"
#event CurePrime "#1# #*#xulous prime#*#"
#event NeriakShock "#*#The golem glows and begins to hum, turning its head toward you.#*#"
#event NeriakChill "#*#Take that one's essence, my pet!#*#"
#event NeriakCold "#*#Sooo cooooold#*#"
#event NeriakPulse "#*#An energy pulse moves toward you.#*#"
#event NeriakSpear "#*#you are pinned to the ground with a spear#*#"
#event Bixie2Red "#*#red cloud forms above#*#"
#event Bixie2Yellow "#*#yellow cloud forms above#*#"
#event Bixie2Safe "#*#spines rains down around#*#"

Sub Event_Bixie2Safe(string line)
/if (${line.Find[${Me}]}) /return Safe
/return 

Sub Event_Bixie2Red(string line)
/if (${line.Find[${Me}]}) {
	/declare tempx float local ${Me.X}
	/declare tempy float local ${Me.Y}
	/moveto loc -932 -2525
	:loop
	/doevents Bixie2Safe
	/if (!${Macro.Return.Find[Safe]}) /goto :loop
	/moveto loc ${tempy} ${tempx}
	/delay 1s
	/delay 6s !${Me.Moving}
}
/return

Sub Event_Bixie2Yellow(string line)
/if (${line.Find[${Me}]}) {
	/declare tempx float local ${Me.X}
	/declare tempy float local ${Me.Y}
	/moveto loc -614 -2444
	:loop
	/doevents Bixie2Safe
	/if (!${Macro.Return.Find[Safe]}) /goto :loop
	/moveto loc ${tempy} ${tempx}
	/delay 1s
	/delay 6s !${Me.Moving}
}
/return

Sub Event_NeriakSpear
/stand
/moveto loc 440.50 -668
/delay 1s
/delay 6s !${Me.Moving}
/delay 6s
/moveto loc 454.06 -504
/delay 1s
/delay 6s !${Me.Moving}
/doevents flush NeriakSpear
/return


Sub Event_CurePrime(string Line,string Person)
/if (!${Person.Find[You]} && (${Me.Class.Name.Equal[Ranger]} || ${Me.Class.Name.Equal[BeastLord]}) ) {
	/delay 3s ${Me.SpellReady[${DiseaseSpell}]}
	/squelch /stick off
	/call CastSpell "${DiseaseSpell}" gem12 ${Spawn[pc ${Person}].ID} 	
}
/doevents flush CurePrime
/return

Sub Event_NeriakCold
/if (${MeleeList.Find[${Me.Class.Name}]}) {
	/bc moving back!
	/squelch /stick 120 moveback
	/delay 12s
	/squelch /stick off
}
/return

Sub Event_NeriakChill(string line)
/if (${line.Find[${Me}]}) {
	/tell ${EventsMaster} I need to run away from the raid got essense emote
	/if (${DoLeash}) /leash off
	/play shock smart
	/delay 10s ${AdvPath.Waypoints} < 1 
	/delay 6s ${Me.Buff[Grave Chill].ID}
	/play shock smart reverse
	/delay 10s ${AdvPath.Waypoints} < 1
}
/return

Sub Event_NeriakShock
/tell ${EventsMaster} I need to run away from the raid shock emote
/if (${DoLeash}) /leash off
/play shock smart
/delay 10s ${AdvPath.Waypoints} < 1 
/delay 6s ${Me.Buff[Sonic Shock].ID} 
/play shock smart reverse
/delay 10s ${AdvPath.Waypoints} < 1
/return

Sub Event_NeriakPulse
/tell ${EventsMaster} I need to run away from the raid from pulse!
/if (${DoLeash}) /leash off
/play pulse smart
/delay 15s ${AdvPath.Waypoints} < 1
/delay 45s ${SpawnCount[npc "An energy pulse" radius 50]}
/play pulse2 smart
/delay 45s ${SpawnCount[npc "An energy pulse" radius 50]}
/play pulse3 smart
/delay 45s ${SpawnCount[npc "An energy pulse" radius 50]}
/play pulse smart reverse
/delay 10s ${AdvPath.Waypoints} < 1
/return


sub Event_Prime1
/tell ${EventsMaster} I NEED A CURE!
/return

Sub Event_danela(string Line, string Person)
/if (${Line.Find[${Me.CleanName}]}) {
	/bc I need to run!
	/play Danela smart
	/delay 10s ${AdvPath.Waypoints} < 1
	/play Danela reverse smart
	/delay 10s ${AdvPath.Waypoints} < 1
	}
/return


Sub Event_ChelsStopDPS
  /echo Stop DPS ${CureList.Find[${Me.Class}]} ${Me.Class}
  /if (!${CureList.Find[${Me.Class}]}) {
    /target myself
	/melee reset
    /delay 16s
  }
/return

Sub Event_VyzhGetClose
  /echo Oh shit move back!1
  /moveto loc ${Spawn[Vyzh`dra the Godslayer].Y} ${Spawn[Vyzh`dra the Godslayer].X}
  /if (!${Defined[VyzhClose]}) {
    /declare VyzhClose int outer 1
  } else {
    /varset VyzhClose 1
  }
  /delay 3s ${Spawn[Vyzh`dra the Godslayer].Distance}<20
/return

Sub Event_VyzhAE
  /if (!${Defined[VyzhClose]}) {
    /declare VyzhClose int outer 0
  } else {
    /varset VyzhClose 0
  }

  :TopOfVyzhAE
   /if (${Spawn[Vyzh`dra the Godslayer].ID}) {
     /call DoLeashPerson
   }
   /doevents
   /delay 1
  /if (${Spawn[Vyzh`dra the Godslayer].Distance}<=150 || ${VyzhClose}) /goto :TopOfVyzhAE
  /echo Vyzh AE all done!!
  /varset VyzhClose 0
/return

Sub Event_KilsevRageOff
  /if (!${Defined[KilsevRaged]}) {
    /declare KilsevRaged int outer 0
  } else {
    /varset KilsevRaged 0
  }
  /echo Rage off!
/return

Sub Event_KilsevRage(string Line, string Person)
  /if (${Person.Equal[${Me.CleanName}]}) {
    /bc I HAVE TO KITE!!!

    /if (!${Defined[KilsevRaged]}) {
      /declare KilsevRaged int outer 1
    } else {
      /varset KilsevRaged 1
    }

    :TopOfKilsevRaged
     /doevents
     /delay 5 !${KilsevRaged}
    /if (${KilsevRaged}) /goto :TopOfKilsevRaged
    /varset VyzhClose 0
  }
/return


Sub Event_Xorbb3
/bc I need to face away from him for a bit
/squelch /stick off
/play xorbbrun smart
/delay 10s ${AdvPath.NextWaypoint} <3
/face loc -478,-604,-451
/if (${MeleeList.Find[${Me.Class.Name}]}) /delay 10s
/return

Sub Event_FindleFireBall
  /bc I NEED to RUN! Have Fireball!
  /target clear
  :TopOfFireBallSub
  /echo running south
  /play FindleFireBall smart
  /delay 1s ${Me.Moving}
  :MoveFireSafeSpot
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :MoveFireSafeSpot
  :WaitFireBallDot
   /delay 1s ${Me.Buff[Engulfing Flames].ID}
   /if (!${Me.Ducking} && !${Me.Moving}) /keypress DUCK
  /if (!${Me.Buff[Engulfing Flames].ID}) /goto :WaitFireBallDot
  /bc I have the fireball DoT on me now!
  :WaitFireBallDotFade
   /if (!${Me.Ducking}) /keypress DUCK
   /delay 1s ${Me.Buff[Engulfing Flames].ID}
  /if (${Me.Buff[Engulfing Flames].ID}) /goto :WaitFireBallDotFade
  :FireBallHere
   /if (${Me.Buff[Engulfing Flames].ID} && !${Me.Ducking}) /keypress DUCK
   /delay 1s ${Spawn[npc "a fireball"].ID} && ${Spawn[npc "a fireball"].Distance}<40
  /if (${Spawn[npc "a fireball"].ID} && ${Spawn[npc "a fireball"].Distance}<40) /goto :FireBallHere
  /if (${Me.Ducking}) /keypress DUCK
  /echo Running back.
  /play FindleFireBall smart reverse
  /delay 1s ${Me.Moving}
  :BackToFireCamp
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :BackToFireCamp
  /if (${Me.Buff[Engulfing Flames].ID}) /goto :TopOfFireBallSub
  /doevents flush FindleFireBall
/return



Sub Event_xorbbfire3
/if (${MeleeList.Find[${Me.Class.Name}]}) {
	/bc moving back!
	/squelch /stick 60 moveback
	/delay 12s
	/squelch /stick off
	}
/return

Sub Event_xorbbwhip
/bc Need to duck!
/duck
/delay 1s
/sit
/delay 1s
/return

Sub Event_xorbbfire2
/if (!${Zone.Name.Equal[bobby]}) /return
/bc Need to duck!
/duck
/delay 1s
/sit
/delay 1s
/return

Sub Event_xorbbfire
/bc running from fire!
/play fireball smart
/delay 1s ${Me.Moving}
/delay 20s !${Me.Moving}
/play Fireball smart reverse
/delay 1s ${Me.Moving}
/delay 20s !${Me.Moving}
/return

Sub Event_Zalikor
/if (!${Zone.ShortName.Equal[breedinggrounds_raid]}) /return
/play Zalikor smart
/delay 1s ${Me.Moving}
:stillmoving 
/if (${AdvPath.NextWaypoint} > 6) /goto :stillmoving
/return

Sub Event_chapterhouse
  /bc I NEED to RUN AWAY!
  /target clear
  /echo running to pool
  /play ChapterPool smart
  /delay 1s ${Me.Moving}
  :MoveChaptSafeSpot
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :MoveChaptSafeSpot
  :WaitChaptDot
   /delay 1s !${Me.Buff[Scorching Bones].ID}
  /if (${Me.Buff[Scorching Bones].ID}) /goto :WaitChaptDot
  /echo Running back to camp
  /play ChapterReturn smart
  /delay 1s ${Me.Moving}
  :BackToChaptCamp
   /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :BackToChaptCamp
/return

Sub Event_cekenar
/moveto loc 1216 -1093
/delay 7s !${Me.Buff[Lightning Charge].ID}
/call leash
/return

sub Event_window
/tell ${EventsMaster} i need to jump out the window
/return

sub Event_Totem
/tell ${EventsMaster} i need to hug totem
/return

Sub Event_Blob
/tell ${EventsMaster} i need to move away from the blob
/return


sub Event_ar1
/if (!${Defined[Safe]}) /declare Safe bool outer false 
/target Aaryonar
/delay 1s
/face away
:safecheck
/doevents arl2
/if (${MeleeList.Find[${Me.Class.Name}]}) /delay 8s
/return

sub event_arl2
/varset Safe TRUE
/return

Sub Event_Sisters
/bc I GOT EMOTE TO MOVE!
/return

Sub Event_ROT
/bc I GOT EMOTE TO RUN!
/moveto loc -988.70 103
/delay 5s
/return

Sub Event_CV2
/bc I GOT EMOTE To RUN!
/moveto loc -750.09 1182.75
/delay 2s
/moveto loc -974 1173
/tell ${EventsMaster} I NEED TO RUN!
/delay 10s
/return

Sub Event_Brells
  /bc I GOT THE EMOTE TO RUN FROM RAID!
/return

Sub Event_BeastOne(line,person)
  /if (${person.Equal[${Me}]}) {
  	/bc DD about to hit me!
  	/bc DD about to hit me!
  	/bc DD about to hit me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_BeastTwo(line,person)
  /if (${person.Equal[${Me}]}) {
  	/bc  Silence about to hit me!
  	/bc  Silence about to hit me!
  	/bc  Silence about to hit me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_BeastThree(line,person)
/if (${line.Find[${Me}]}) {
  	/bc  mate about to ae on me!
  	/bc  mate about to ae on me!
  	/bc  mate about to ae on me!
  /moveto loc -2807, -288
  /delay 20s 
}
/return

Sub Event_Brekt
/if (!${MeleeList.Find[${Me.Class.Name}]}) /Return
/stick 100 moveback
/delay 6s
/target clear
/return

Sub Event_mindblightNW
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 215 71
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightSW
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 201 -79
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightSE
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 92 82 
/delay 20s !${MoveTo.Moving}
/return

Sub Event_mindblightNE
/if (${Spawn[npc The Mindblight].ID}) /return
/moveto loc 94 -86
/delay 20s !${MoveTo.Moving}
/return

Sub Event_Back
|   /declare MeleeList string local Bard|Ranger|Berserker|Rogue|Warrior|Paladin|ShadowKnight|Beastlord|Monk
   /if (${MeleeList.Find[${Me.Class}]}) /squelch /stick ${StickSetting} behind
   /return

Sub Event_Front
|   /declare MeleeList string local Bard|Ranger|Berserker|Rogue|Warrior|Paladin|ShadowKnight|Beastlord|Monk
   /if (${MeleeList.Find[${Me.Class}]}) /squelch /stick ${StickSetting} front
   /return
   
Sub Event_mindshear
/tell ${EventsMaster} i need to move away from the raid
/return

Sub event_hatchet1
  /i say I NEED TO RUN AWAY
  /squelch /stick pause
  /declare running          int   local
  /declare distanceNow      float local
  /declare distanceBefore   float local
  /declare distanceModifier int   local
  /declare MoveToID         int   local ${Spawn[Hatchet].ID}
  /declare StopDistance     int   local 200
  /declare distanceTimer    timer 15
  /varset  distanceBefore   ${Spawn[${MoveToID}].Distance}
  /varset  distanceModifier 1
  /varset  running 0

  :moveAway
  /squelch /face fast away id ${MoveToID}

  /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
    /keypress forward
    /i say I am far from Hatchet!!!
    /return
  }   
  /if (${distanceTimer}==0) {
    /if (${Me.Sneaking}) {
      /varset distanceModifier 2
    } else {
      /varset distanceModifier 1
    }
    /varset distanceNow ${Spawn[${MoveToID}].Distance}
    /if (${Math.Calc[${distanceBefore}-${distanceNow}]}<${Math.Calc[10/${distanceModifier}]}) {
      /keypress forward
      /if (${Math.Rand[99]}>50) {
        /keypress strafe_right hold
      } else {
        /keypress strafe_left hold
      }
      /delay 1s
      /keypress strafe_right
      /keypress strafe_left
      /keypress forward hold
    }
    /varset distanceBefore ${Spawn[${MoveToID}].Distance}
    /varset distanceTimer 15
  }
  /if (${running}==0) {
    /keypress forward
    /if (${Spawn[${MoveToID}].Distance}<=${StopDistance}) {
      /varset running 1
      /keypress forward hold
    }
  } else {
    /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
      /varset running 0
      /keypress forward
    }
    /goto :moveAway
  }
  /return

Sub event_hatchet2
  /i say I NEED TO RUN BETWEEN HIS LEGS
  /declare running          int local
  /declare distanceNow      float local
  /declare distanceBefore   float local
  /declare distanceModifier int   local
  /declare MoveToID         int   local ${Spawn[Hatchet].ID}
  /declare StopDistance     int   local 6
  /declare distanceTimer    timer 15
  /varset  distanceBefore   ${Spawn[${MoveToID}].Distance}
  /varset  distanceModifier 1
  /varset  running 0

  :moveToSpawn
  /squelch /face fast nolook id ${MoveToID}
  /if (${Spawn[${MoveToID}].Distance}<${StopDistance}) {
    /keypress forward
    /i say I am at Hatchet!!!
    /return
  }
  /if (${distanceTimer}==0) {
    /if (${Me.Sneaking}) {
      /varset distanceModifier 2
    } else {
      /varset distanceModifier 1
    }
    /varset distanceNow ${Spawn[${MoveToID}].Distance}
    /if (${Math.Calc[${distanceBefore}-${distanceNow}]}<${Math.Calc[10/${distanceModifier}]}) {
      /keypress forward
      /if (${Math.Rand[99]}>50) {
        /keypress strafe_right hold
      } else {
        /keypress strafe_left hold
      }
    /delay 1s
    /keypress strafe_right
    /keypress strafe_left
    /keypress forward hold
    }
  /varset distanceBefore ${Spawn[${MoveToID}].Distance}
  /varset distanceTimer 15
  }
  /if (${running}==0) {
    /keypress forward
    /if (${Spawn[${MoveToID}].Distance}>=${StopDistance}) {
      /varset running 1
      /keypress forward hold
    }
  } else {
    /if (${Spawn[${MoveToID}].Distance}<${StopDistance}) {
      /varset running 0
      /keypress forward
    }
  }
  /goto :moveToSpawn
  /return

Sub event_hatchet3
  /tell ${EventsMaster} I NEED TO DUCK
  /if (!${Me.Ducking}) /keypress duck
  /delay 15s
  /return

Sub event_hatchet4
  /tell ${EventsMaster} I NEED TO KITE HATCHET!!
  /return

Sub event_hatchet6
  /tell ${EventsMaster} DANGER IS GONE!
  /if (${Me.Ducking}) /keypress duck
  /return

Sub event_doom
  /tell ${EventsMaster} I got DT!
  /if (!${FindItem[distillate of immunization VI].Timer} && ${Me.Buff[mark of death].ID}) /call cast "distillate of immunization VI" item 1s
  /if (!${FindItem[distillate of celestial healing xiii].Timer}) /call cast "distillate of celestial healing xiii" item 1s
  /return

Sub event_GazeYou
  /if (!${Spawn[npc "overlord mata muram"].ID}) /return
  /declare OldItem string local

  /popup CLICK ON THE MASK!
  /tell ${EventsMaster} I GOT MASK EMOTE!

  /if ( ${Me.Casting.ID} ) /stopcast
  /if (${Me.Inventory[face].Name.NotEqual[Mirrored Mask]}) {
    /varset OldItem ${Me.Inventory[face].Name}
    /exchange "Mirrored Mask" face
    /delay 1
    /call Cast "mirrored mask" item 3s
    /exchange "${OldItem}" face
  } else {
    /call Cast "${Me.Inventory[face].Name}" item 3s
  }
  /return

Sub Event_smotherdecay
  /tell ${EventsMaster} I'm snared/slow i need to click on the blue crystal
  /return

Sub Event_curseofthefirstborn
  /tell ${EventsMaster} My stats are deduced. i need to click on the yellow crystal.
  /return

Sub Event_presentofthefirstborn
  /tell ${EventsMaster} I'm silenced. I need to click on the red crystal
  /return

Sub Event_plagueofmana
  /tell ${EventsMaster} I have the 3k dot on me. I need to click on the green crystal.
  /return

Sub Event_Silence
  /tell ${EventsMaster} i'm silenced!
  /return

Sub Event_Adds
  /tell ${EventsMaster} The adds are going to spawn right on top of me!
  /return

Sub Event_UquaKey(string line,string key)
  /tell ${EventsMaster} ${key}
  /return

Sub Event_queenlocation
  /tell ${EventsMaster} Queen is heading right for me
  /return

Sub Event_performer
  /tell ${EventsMaster} I need to recite A line!
  /return

Sub Event_devlin
  /tell ${EventsMaster} i need to remove A piece of gear!
  /return

Sub Event_devlin2
  /tell ${EventsMaster} i need to remove my weapon!
  /itemnotify mainhand leftmouseup
  /delay 9s
  /autoinventory
  /return

Sub SpeakLine
  :speakloop
  /attack off
  /if (${Spawn[${Param0}].Distance}>50) {
    /popup Move Closer To ${Param0}
    /delay 1s
    /goto :speakloop
  } else {
    /target ${Param0}
    /delay 1s ${Target.CleanName.Equal[${Param0}]}
    /delay ${Math.Rand[15]}
    /say ${Param1}
  }
  /squelch /target clear
  /return

Sub Event_Randal1
  /call SpeakLine "Randal Reedsea" "Where'er he smelled Jumjum he'd pick it."
  /return

Sub Event_Randal2
  /call SpeakLine "Randal Reedsea" "The halflings grew cross"
  /return

Sub Event_Randal3
  /call SpeakLine "Randal Reedsea" "When their profits were lost,"
  /return

Sub Event_Randal4
  /call SpeakLine "Randal Reedsea" "screamin', 'Where is that brownie? I'll kick it!'"
  /return

Sub Event_Randal5
  /call SpeakLine "Randal Reedsea" "Ol' Nilipus hailed from Misty Thicket."
  /return

Sub Event_Seth1
  /call SpeakLine "Seth Kimble" "Time bleeds like a wound that's lost all meaning."
  /return

Sub Event_Seth2
  /call SpeakLine "Seth Kimble" "It's a long winter in the swirling chaotic void."
  /return

Sub Event_Seth3
  /call SpeakLine "Seth Kimble" "This is my torture,"
  /return

Sub Event_Seth4
  /call SpeakLine "Seth Kimble" "my pain and suffering!"
  /return

Sub Event_Seth5
  /call SpeakLine "Seth Kimble" "Pinch me, O'Death. . ."
  /return

Sub Event_Seth6
  /call SpeakLine "Seth Kimble" "Another night, in eternal darkness."
  /return

Sub Event_Aelfric1
  /call SpeakLine "Aelfric the Flautist" "Where will you be?"
  /return

Sub Event_Aelfric2
  /call SpeakLine "Aelfric the Flautist" "Dreaming with me."
  /return

Sub Event_Aelfric3
  /call SpeakLine "Aelfric the Flautist" "Please,"
  /return

Sub Event_Aelfric4
  /call SpeakLine "Aelfric the Flautist" "everybody, hear the music."
  /return

Sub Event_Aelfric5
  /call SpeakLine "Aelfric the Flautist" "Touched tenderly."
  /return

Sub Event_Britton1
  /call SpeakLine "Britton Harmony" "it felt like the end of my days."
  /return

Sub Event_Britton2
  /call SpeakLine "Britton Harmony" "Until I suddenly,"
  /return

Sub Event_Britton3
  /call SpeakLine "Britton Harmony" "Suddenly realized"
  /return

Sub Event_Britton4
  /call SpeakLine "Britton Harmony" "this life was better off alone."
  /return

Sub Event_Britton5
  /call SpeakLine "Britton Harmony" "Solitude was the best gift you ever gave me."
  /return

Sub Event_Britton6
  /call SpeakLine "Britton Harmony" "When she and I split ways,"
  /return

Sub Event_Mayong
  /tell ${EventsMaster} i need to get away from mayong!
  /return

Sub Event_fero
  /tell ${EventsMaster} i have fero i need to get away from the raid!
  /return

Sub Event_wrath
  /tell ${EventsMaster} i have wrath. i need to get away from the raid!
  /return

Sub Event_vergalid1
  /tell ${EventsMaster} i'm about to be banished!
  /if (${Me.Buff[Dooming Exile].ID} && ${Me.AltAbilityReady[radiant cure]}) /call cast "radiant cure" alt 3s
  /if (${Me.Buff[Dooming Exile].ID}) {
    /target npc an infused crystal
    /stick 5
    /attack on
    /delay 6s !${Me.Buff[Dooming Exile].ID}
  }
  /return

Sub Event_vergalid2
  /if (${Me.Buff[Breed of Corruption].ID} && ${Me.AltAbilityReady[radiant cure]}) /call cast "radiant cure" alt 3s
  /if (${Me.Buff[Breed of Corruption].ID}) {
    /target npc an infused crystal
    /stick 5
    /attack on
    /delay 6s !${Me.Buff[Breed of Corruption].ID}
  }
  /return

Sub Event_banish
  /tell ${EventsMaster} i got banished!
  /return

Sub Event_vertigo
  /tell ${EventsMaster} i got the drunk dot on me
  /return

Sub Event_vertigo2
  /tell ${EventsMaster} i just got warped
  /stick off
  /return

Sub Event_king
  /i say I'm getting the archer emote
  /return

Sub event_deepscar(line,person)
  /if ( ${person.Equal[${Me}]})  /tell ${EventsMaster} I'm getting the boulders emote!
  /return

Sub Event_irissa
  /tell ${EventsMaster} I GOT IRISSA's DEBUFF!
  /return

Sub Event_QueenAE
  /bc Getting away from Queen
  /if (${Spawn[Queen Malarian].Distance}>30) {
    /bc Far enough from Queen
    /return
  }
  /target clear
  /play QueenAE smart
  /return

Sub Event_QueenAdd
  /bc I NEED to RUN AWAY!
  /target clear
  /play QueenAdd smart
  /delay 1s ${Me.Moving}
  :MoveToQueenSafeSpot
  /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :MoveToQueenSafeSpot
  :CheckQueenAE
  /delay 1s ${Me.Buff[Wave of Infestation].ID}
  /if (!${Me.Buff[Wave of Infestation].ID}) /goto :CheckQueenAE
  :CureQueenAE
  /delay 1s !${Me.Buff[Wave of Infestation].ID}
  /if (${Me.Buff[Wave of Infestation].ID}) /goto :CureQueenAE
  /play RunToQueenCamp
  /delay 1s ${Me.Moving}
  :BackToQueenCamp
  /delay 1s !${Me.Moving}
  /if (${Me.Moving}) /goto :BackToQueenCamp
  /return

Sub Event_Meldrath11
  /tell ${EventsMaster} I GOT MELDRATH AE
  /return

Sub Event_Meldrath2
  /tell ${EventsMaster} BOMB COMING to Me
  /return

Sub Event_charge
  /tell ${EventsMaster} I need cure corruption quick
  /return

Sub Event_Sleeper
  /if (!${Defined[SleeperCastTimer]}) {
    /declare SleeperCastTimer int outer ${Macro.RunTime}
    /echo Declaring SleeperCastTimer at 10s
  } else {
    /varset SleeperCastTimer ${Math.Calc[${Macro.RunTime}+10]}
    /echo Reseting SleeperCastTimer at 10s
  }
  /if (!${Defined[SleeperTimer]}) {
  	/declare SleeperTimer timer outer 10s
  } else {
  	/varset SleeperTimer 10s
  }
/return

Sub Event_Goodnight
  /camp desktop
  /end
  /return
